### ISSUE TITLE
Enable server usage

### ISSUE THREAD

**Issue by blakeembrey** [cantide5ga/typed-react-dom#2]
It should be possible to use the `server.d.ts` file like https://github.com/blakeembrey/react-free-style/blob/master/src/react-free-style.spec.ts#L5.

**Comment by blakeembrey** [comment]
In case you're not sure how to enable this with `typings`, it's just a matter for creating `server.d.ts` and adding `"files": ["server.d.ts"]` into `typings.json`.

**Comment by cantide5ga** [comment]
Verified with your linked react-free-style test.

**Comment by blakeembrey** [comment]
Thanks!
