### ISSUE TITLE
Question about server.d.ts

### ISSUE THREAD

**Issue by bloadvenro** [cantide5ga/typed-react-dom#5]
I installed react-dom typings via typings cli utility, but there is no server.d.ts file inside `typings/modules/react-dom`

The command was

```
typings i -S npm~react-dom
```

I cannot import {renderToString} from 'react-dom/server'

please tell me what am I doing wrong

UPD

I've read the source code and found that files were merged, but I obviously do not understand why I cannot import react-dom/server (

**Comment by cantide5ga** [comment]
Typings aggregates everything in `index.d.ts` located in `typings/modules/react-dom`.  Can you confirm the namespace `ReactDomServer` is in there?

Also the registry to the updated react-dom typedef was just merged midday yesterday.  But I think you already knew that.
